const words = [
    // 💬 Фразы и общение
    { ro: "Bună ziua", ru: "Добрый день", cat: "💬 Фразы", emoji: "☀️" },
    { ro: "Bună dimineața", ru: "Доброе утро", cat: "💬 Фразы", emoji: "🌅" },
    { ro: "Bună seara", ru: "Добрый вечер", cat: "💬 Фразы", emoji: "🌇" },
    { ro: "Noapte bună", ru: "Доброй ночи", cat: "💬 Фразы", emoji: "🌙" },
    { ro: "La revedere / Pa / Te pup", ru: "До свидания / Пока / Целую", cat: "💬 Фразы", emoji: "👋" },
    { ro: "O zi bună / frumoasă", ru: "Хорошего / красивого дня", cat: "💬 Фразы", emoji: "✨" },
    { ro: "Ce faci? / Ce faceți?", ru: "Как дела? / Что делаете?", cat: "💬 Фразы", emoji: "💬" },
    { ro: "Bine / Foarte bine / Rău", ru: "Хорошо / Очень хорошо / Плохо", cat: "💬 Фразы", emoji: "👍" },
    { ro: "Așa și așa", ru: "Так себе", cat: "💬 Фразы", emoji: "🤷‍♀️" },
    { ro: "Am o întrebare", ru: "У меня вопрос", cat: "💬 Фразы", emoji: "❓" },
    { ro: "Cum te cheamă? / Cum te numești?", ru: "Как тебя зовут?", cat: "💬 Фразы", emoji: "🪪" },
    { ro: "Mă numesc Sasha.", ru: "Меня зовут Саша.", cat: "💬 Фразы", emoji: "🙋‍♀️" },
    { ro: "Câți ani ai?", ru: "Сколько тебе лет?", cat: "💬 Фразы", emoji: "🎂" },
    { ro: "Eu am 20 de ani", ru: "Мне 20 лет", cat: "💬 Фразы", emoji: "🎉" },
    { ro: "De unde ești?", ru: "Откуда ты?", cat: "💬 Фразы", emoji: "🌍" },
    { ro: "Eu sunt din Ucraina", ru: "Я из Украины", cat: "💬 Фразы", emoji: "🇺🇦" },
    { ro: "Îmi pare bine!", ru: "Мне приятно!", cat: "💬 Фразы", emoji: "🤝" },
    { ro: "La fel", ru: "Взаимно / Мне тоже", cat: "💬 Фразы", emoji: "⭐" },
    { ro: "Dar tu?", ru: "А ты?", cat: "💬 Фразы", emoji: "👉" },
    { ro: "Cu ce vă ocupați?", ru: "Чем вы занимаетесь?", cat: "💬 Фразы", emoji: "💼" },
    { ro: "Hai să ne jucăm", ru: "Давай играть", cat: "💬 Фразы", emoji: "🧸" },
    { ro: "Hai la o bere?", ru: "Пойдем на пиво?", cat: "💬 Фразы", emoji: "🍺" },
    { ro: "Ce dată este astăzi?", ru: "Какое число сегодня?", cat: "💬 Фразы", emoji: "📅" },
    { ro: "Astăzi este 15 septembrie.", ru: "Сегодня 15 сентября.", cat: "💬 Фразы", emoji: "🗓" },
    { ro: "Ce zi este astăzi?", ru: "Какой день сегодня?", cat: "💬 Фразы", emoji: "📆" },

    // 🛒 Продукты и Еда
    { ro: "Înghețată", ru: "Мороженое", cat: "🛒 Продукты и Еда", emoji: "🍨" },
    { ro: "Lapte", ru: "Молоко", cat: "🛒 Продукты и Еда", emoji: "🥛" },
    { ro: "Lapte fără lactoză", ru: "Безлактозное молоко", cat: "🛒 Продукты и Еда", emoji: "🥛" },
    { ro: "Iaurt", ru: "Йогурт", cat: "🛒 Продукты и Еда", emoji: "🥣" },
    { ro: "Brânză de vaci", ru: "Творог", cat: "🛒 Продукты и Еда", emoji: "🧀" },
    { ro: "Cașcaval", ru: "Твердый сыр", cat: "🛒 Продукты и Еда", emoji: "🧀" },
    { ro: "Telemea", ru: "Брынза", cat: "🛒 Продукты и Еда", emoji: "🧀" },
    { ro: "Smântână", ru: "Сметана", cat: "🛒 Продукты и Еда", emoji: "🥣" },
    { ro: "Unt", ru: "Сливочное масло", cat: "🛒 Продукты и Еда", emoji: "🧈" },
    { ro: "Carne de porc", ru: "Свинина", cat: "🛒 Продукты и Еда", emoji: "🥩" },
    { ro: "Carne de pui", ru: "Курятина", cat: "🛒 Продукты и Еда", emoji: "🍗" },
    { ro: "Carne de vită", ru: "Говядина", cat: "🛒 Продукты и Еда", emoji: "🥩" },
    { ro: "Crenvurști", ru: "Сосиски", cat: "🛒 Продукты и Еда", emoji: "🌭" },
    { ro: "Salam", ru: "Колбаса", cat: "🛒 Продукты и Еда", emoji: "🥓" },
    { ro: "Șuncă", ru: "Ветчина", cat: "🛒 Продукты и Еда", emoji: "🥓" },
    { ro: "Șnițel", ru: "Шницель", cat: "🛒 Продукты и Еда", emoji: "🍛" },
    { ro: "Pește", ru: "Рыба", cat: "🛒 Продукты и Еда", emoji: "🐟" },
    { ro: "Creveți", ru: "Креветки", cat: "🛒 Продукты и Еда", emoji: "🍤" },
    { ro: "Măr", ru: "Яблоко", cat: "🛒 Продукты и Еда", emoji: "🍎" },
    { ro: "Pară", ru: "Груша", cat: "🛒 Продукты и Еда", emoji: "🍐" },
    { ro: "Banană", ru: "Банан", cat: "🛒 Продукты и Еда", emoji: "🍌" },
    { ro: "Portocală", ru: "Апельсин", cat: "🛒 Продукты и Еда", emoji: "🍊" },
    { ro: "Lămâie", ru: "Лимон", cat: "🛒 Продукты и Еда", emoji: "🍋" },
    { ro: "Struguri", ru: "Виноград", cat: "🛒 Продукты и Еда", emoji: "🍇" },
    { ro: "Căpșună", ru: "Клубника", cat: "🛒 Продукты и Еда", emoji: "🍓" },
    { ro: "Cireașă", ru: "Черешня", cat: "🛒 Продукты и Еда", emoji: "🍒" },
    { ro: "Piersică", ru: "Персик", cat: "🛒 Продукты и Еда", emoji: "🍑" },
    { ro: "Pepene roșu", ru: "Арбуз", cat: "🛒 Продукты и Еда", emoji: "🍉" },
    { ro: "Roșie", ru: "Помидор", cat: "🛒 Продукты и Еда", emoji: "🍅" },
    { ro: "Castravete", ru: "Огурец", cat: "🛒 Продукты и Еда", emoji: "🥒" },
    { ro: "Cartof", ru: "Картошка", cat: "🛒 Продукты и Еда", emoji: "🥔" },
    { ro: "Ceapă", ru: "Лук", cat: "🛒 Продукты и Еда", emoji: "🧅" },
    { ro: "Usturoi", ru: "Чеснок", cat: "🛒 Продукты и Еда", emoji: "🧄" },
    { ro: "Morcov", ru: "Морковь", cat: "🛒 Продукты и Еда", emoji: "🥕" },
    { ro: "Varză", ru: "Капуста", cat: "🛒 Продукты и Еда", emoji: "🥬" },
    { ro: "Dovlecel", ru: "Кабачок", cat: "🛒 Продукты и Еда", emoji: "🥒" },
    { ro: "Vânătă", ru: "Баклажан", cat: "🛒 Продукты и Еда", emoji: "🍆" },
    { ro: "Ciupercă", ru: "Гриб", cat: "🛒 Продукты и Еда", emoji: "🍄" },
    { ro: "Pâine", ru: "Хлеб", cat: "🛒 Продукты и Еда", emoji: "🍞" },
    { ro: "Covrigi", ru: "Бублик", cat: "🛒 Продукты и Еда", emoji: "🥯" },
    { ro: "Chifle", ru: "Булочка", cat: "🛒 Продукты и Еда", emoji: "🍞" },
    { ro: "Plăcintă", ru: "Пирог", cat: "🛒 Продукты и Еда", emoji: "🥧" },
    { ro: "Clătită", ru: "Блинчик", cat: "🛒 Продукты и Еда", emoji: "🥞" },
    { ro: "Apă", ru: "Вода", cat: "🛒 Продукты и Еда", emoji: "💧" },
    { ro: "Suc", ru: "Сок", cat: "🛒 Продукты и Еда", emoji: "🧃" },
    { ro: "Vin", ru: "Вино", cat: "🛒 Продукты и Еда", emoji: "🍷" },
    { ro: "Bere", ru: "Пиво", cat: "🛒 Продукты и Еда", emoji: "🍺" },
    { ro: "Ceai", ru: "Чай", cat: "🛒 Продукты и Еда", emoji: "🍵" },

    // 💼 Жизнь и Профессии
    { ro: "Albastru", ru: "Синий", cat: "💼 Жизнь и Профессии", emoji: "🔵" },
    { ro: "Pălărie", ru: "Шляпа", cat: "💼 Жизнь и Профессии", emoji: "👒" },
    { ro: "Soare", ru: "Солнце", cat: "💼 Жизнь и Профессии", emoji: "☀️" },
    { ro: "Șaizeci și cinci", ru: "65", cat: "💼 Жизнь и Профессии", emoji: "65" },
    { ro: "Șaptezeci și cinci", ru: "75", cat: "💼 Жизнь и Профессии", emoji: "75" },
    { ro: "Liber", ru: "Свободно", cat: "💼 Жизнь и Профессии", emoji: "🟢" },
    { ro: "Ocupat", ru: "Занято", cat: "💼 Жизнь и Профессии", emoji: "🔴" },
    { ro: "Bărbat", ru: "Мужчина", cat: "💼 Жизнь и Профессии", emoji: "👨" },
    { ro: "Femeie", ru: "Женщина", cat: "💼 Жизнь и Профессии", emoji: "👩" },
    { ro: "Băiat", ru: "Мальчик", cat: "💼 Жизнь и Профессии", emoji: "👦" },
    { ro: "Fată", ru: "Девочка", cat: "💼 Жизнь и Профессии", emoji: "👧" },
    { ro: "Inginer", ru: "Инженер", cat: "💼 Жизнь и Профессии", emoji: "💻" },
    { ro: "Doctor", ru: "Врач", cat: "💼 Жизнь и Профессии", emoji: "🩺" },
    { ro: "Asistentă medicală", ru: "Медсестра", cat: "💼 Жизнь и Профессии", emoji: "👩‍⚕️" },
    { ro: "Polițist", ru: "Полицейский", cat: "💼 Жизнь и Профессии", emoji: "👮" },
    { ro: "Pompier", ru: "Пожарный", cat: "💼 Жизнь и Профессии", emoji: "👨‍🚒" },
    { ro: "Educatoare", ru: "Воспитательница", cat: "💼 Жизнь и Профессии", emoji: "🏫" },
    { ro: "Învățător", ru: "Учитель младших классов", cat: "💼 Жизнь и Профессии", emoji: "📚" },
    { ro: "Profesor", ru: "Учитель старших классов", cat: "💼 Жизнь и Профессии", emoji: "👨‍🏫" },
    { ro: "Bucătar", ru: "Повар", cat: "💼 Жизнь и Профессии", emoji: "👨‍🍳" },
    { ro: "Brutar", ru: "Пекарь", cat: "💼 Жизнь и Профессии", emoji: "🥖" },
    { ro: "Marinar", ru: "Моряк", cat: "💼 Жизнь и Профессии", emoji: "⚓" },
    { ro: "Chelner", ru: "Официант", cat: "💼 Жизнь и Профессии", emoji: "🍽️" },
    { ro: "Veterinar", ru: "Ветеринар", cat: "💼 Жизнь и Профессии", emoji: "🐾" },
    { ro: "Croitor", ru: "Портной", cat: "💼 Жизнь и Профессии", emoji: "🧵" },
    { ro: "Vânzător", ru: "Продавец", cat: "💼 Жизнь и Профессии", emoji: "🛍️" },
    { ro: "Zidar", ru: "Строитель", cat: "💼 Жизнь и Профессии", emoji: "🧱" },
    { ro: "Fermier", ru: "Фермер", cat: "💼 Жизнь и Профессии", emoji: "🚜" },
    { ro: "Instalator", ru: "Сантехник", cat: "💼 Жизнь и Профессии", emoji: "🔧" },
    { ro: "Contabil", ru: "Бухгалтер", cat: "💼 Жизнь и Профессии", emoji: "📊" },
    { ro: "Dentist", ru: "Стоматолог", cat: "💼 Жизнь и Профессии", emoji: "🦷" },
    { ro: "Programator", ru: "Программист", cat: "💼 Жизнь и Профессии", emoji: "💻" },
    { ro: "Manager", ru: "Менеджер", cat: "💼 Жизнь и Профессии", emoji: "📈" },
    { ro: "Poștaș", ru: "Почтальон", cat: "💼 Жизнь и Профессии", emoji: "✉" },
    { ro: "Șofer", ru: "Водитель", cat: "💼 Жизнь и Профессии", emoji: "🚗" },
    { ro: "Măturător stradal", ru: "Дворник", cat: "💼 Жизнь и Профессии", emoji: "🧹" },
    { ro: "Cântăreț", ru: "Певец", cat: "💼 Жизнь и Профессии", emoji: "🎤" },
    { ro: "Actor", ru: "Актер", cat: "💼 Жизнь и Профессии", emoji: "🎭" },
    { ro: "Pictor", ru: "Художник", cat: "💼 Жизнь и Профессии", emoji: "🎨" },
    { ro: "Scriitor", ru: "Писатель", cat: "💼 Жизнь и Профессии", emoji: "✍️" },
    { ro: "Pescar", ru: "Рыбак", cat: "💼 Жизнь и Профессии", emoji: "🎣" },
    { ro: "Casnică", ru: "Домохозяйка", cat: "💼 Жизнь и Профессии", emoji: "🏠" },
    { ro: "Luni", ru: "Понедельник", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Marți", ru: "Вторник", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Miercuri", ru: "Среда", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Joi", ru: "Четверг", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Vineri", ru: "Пятница", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Sâmbătă", ru: "Суббота", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Duminică", ru: "Воскресенье", cat: "💼 Жизнь и Профессии", emoji: "📅" },

    // 🧠 Тело и Здоровье
    { ro: "Cap", ru: "Голова", cat: "🧠 Тело и Здоровье", emoji: "🗣️" },
    { ro: "Păr", ru: "Волосы", cat: "🧠 Тело и Здоровье", emoji: "💇" },
    { ro: "Ureche", ru: "Ухо", cat: "🧠 Тело и Здоровье", emoji: "👂" },
    { ro: "Nas", ru: "Нос", cat: "🧠 Тело и Здоровье", emoji: "👃" },
    { ro: "Gură", ru: "Рот", cat: "🧠 Тело и Здоровье", emoji: "👄" },
    { ro: "Dinte", ru: "Зуб", cat: "🧠 Тело и Здоровье", emoji: "🦷" },
    { ro: "Limbă", ru: "Язык", cat: "🧠 Тело и Здоровье", emoji: "👅" },
    { ro: "Ochi", ru: "Глаз", cat: "🧠 Тело и Здоровье", emoji: "👁️" },
    { ro: "Gât", ru: "Шея", cat: "🧠 Тело и Здоровье", emoji: "🧣" },
    { ro: "Mână", ru: "Рука", cat: "🧠 Тело и Здоровье", emoji: "✋" },
    { ro: "Deget", ru: "Палец", cat: "🧠 Тело и Здоровье", emoji: "☝️" },
    { ro: "Burtă", ru: "Живот", cat: "🧠 Тело и Здоровье", emoji: "🤰" },
    { ro: "Picior", ru: "Нога", cat: "🧠 Тело и Здоровье", emoji: "🦵" },
    { ro: "Genunchi", ru: "Колено", cat: "🧠 Тело и Здоровье", emoji: "🦵" },
    { ro: "Inimă", ru: "Сердце", cat: "🧠 Тело и Здоровье", emoji: "❤️" },
    { ro: "Spate", ru: "Спина", cat: "🧠 Тело и Здоровье", emoji: "🔙" },

    // 🐾 Животный мир
    { ro: "Câine", ru: "Собака", cat: "🐾 Животный мир", emoji: "🐕" },
    { ro: "Pisică", ru: "Кошка", cat: "🐾 Животный мир", emoji: "🐈" },
    { ro: "Veveriță", ru: "Белка", cat: "🐾 Животный мир", emoji: "🐿️" },
    { ro: "Vacă", ru: "Корова", cat: "🐾 Животный мир", emoji: "🐄" },
    { ro: "Cal", ru: "Лошадь", cat: "🐾 Животный мир", emoji: "🐎" },
    { ro: "Porc", ru: "Свинья", cat: "🐾 Животный мир", emoji: "🐖" },
    { ro: "Iepure", ru: "Кролик", cat: "🐾 Животный мир", emoji: "🐇" },
    { ro: "Rață", ru: "Утка", cat: "🐾 Животный мир", emoji: "🦆" },
    { ro: "Gâscă", ru: "Гусь", cat: "🐾 Животный мир", emoji: "🪿" },
    { ro: "Leu", ru: "Лев", cat: "🐾 Животный мир", emoji: "🦁" },
    { ro: "Tigru", ru: "Тигр", cat: "🐾 Животный мир", emoji: "🐅" },
    { ro: "Urs", ru: "Медведь", cat: "🐾 Животный мир", emoji: "🐻" },
    { ro: "Lup", ru: "Волк", cat: "🐾 Животный мир", emoji: "🐺" },
    { ro: "Vulpe", ru: "Лиса", cat: "🐾 Животный мир", emoji: "🦊" },
    { ro: "Maimuță", ru: "Обезьяна", cat: "🐾 Животный мир", emoji: "🐵" },
    { ro: "Elefant", ru: "Слон", cat: "🐾 Животный мир", emoji: "🐘" },
    { ro: "Girafă", ru: "Жираф", cat: "🐾 Животный мир", emoji: "🦒" },
    { ro: "Albină", ru: "Пчела", cat: "🐾 Животный мир", emoji: "🐝" },
    { ro: "Fluture", ru: "Бабочка", cat: "🐾 Животный мир", emoji: "🦋" },
    { ro: "Păianjen", ru: "Паук", cat: "🐾 Животный мир", emoji: "🕷️" },
    { ro: "Furnică", ru: "Муравей", cat: "🐾 Животный мир", emoji: "🐜" }
];

const verbConjugations = [
    { verb: "a fi (быть)", pronoun: "Eu (Я)", form: "sunt", options: ["sunt", "ești", "este", "suntem"] },
    { verb: "a fi (быть)", pronoun: "Tu (Ты)", form: "ești", options: ["sunt", "ești", "sunteți", "este"] },
    { verb: "a fi (быть)", pronoun: "El / Ea (Он/Она)", form: "este", options: ["sunt", "este", "suntem", "ești"] },
    { verb: "a fi (быть)", pronoun: "Noi (Мы)", form: "suntem", options: ["suntem", "sunteți", "sunt", "este"] },
    { verb: "a fi (быть)", pronoun: "Voi / Dvs. (Вы)", form: "sunteți", options: ["sunteți", "suntem", "ești", "sunt"] },
    { verb: "a fi (быть)", pronoun: "Ei / Ele (Они)", form: "sunt", options: ["sunt", "este", "suntem", "sunteți"] },
    
    { verb: "a avea (иметь)", pronoun: "Eu (Я)", form: "am", options: ["am", "ai", "are", "avem"] },
    { verb: "a avea (иметь)", pronoun: "Tu (Ты)", form: "ai", options: ["am", "ai", "aveți", "au"] },
    { verb: "a avea (иметь)", pronoun: "El / Ea (Он/Она)", form: "are", options: ["avem", "are", "ai", "au"] },
    { verb: "a avea (иметь)", pronoun: "Noi (Мы)", form: "avem", options: ["aveți", "avem", "am", "are"] },
    { verb: "a avea (иметь)", pronoun: "Voi / Dvs. (Вы)", form: "aveți", options: ["avem", "aveți", "au", "ai"] },
    { verb: "a avea (иметь)", pronoun: "Ei / Ele (Они)", form: "au", options: ["are", "am", "au", "aveți"] },

    { verb: "a cumpăra (покупать)", pronoun: "Eu (Я)", form: "cumpăr", options: ["cumpăr", "cumperi", "cumpără", "cumpărăm"] },
    { verb: "a cumpăra (покупать)", pronoun: "Tu (Ты)", form: "cumperi", options: ["cumpăr", "cumperi", "cumpărați", "cumpără"] },
    { verb: "a cumpăra (покупать)", pronoun: "El / Ea (Он/Она)", form: "cumpără", options: ["cumperi", "cumpără", "cumpărăm", "cumpărați"] },
    { verb: "a cumpăra (покупать)", pronoun: "Noi (Мы)", form: "cumpărăm", options: ["cumpărați", "cumpărăm", "cumpăr", "cumpără"] },
    { verb: "a cumpăra (покупать)", pronoun: "Voi / Dvs. (Вы)", form: "cumpărați", options: ["cumperi", "cumpărați", "cumpărăm", "cumpăr"] },
    { verb: "a cumpăra (покупать)", pronoun: "Ei / Ele (Они)", form: "cumpără", options: ["cumpără", "cumpăr", "cumpărați", "cumperi"] }
];