// database.js — База данных слов, фраз и глаголов для тренажера румынского языка

const words = [
    // 💬 Фразы и общение
    { ro: "Bună ziua", ru: "Добрый день", cat: "💬 Фразы", emoji: "☀️" },
    { ro: "Bună dimineața", ru: "Доброе утро", cat: "💬 Фразы", emoji: "🌅" },
    { ro: "Bună seara", ru: "Добрый вечер", cat: "💬 Фразы", emoji: "🌇" },
    { ro: "Noapte bună", ru: "Доброй ночи", cat: "💬 Фразы", emoji: "🌙" },
    { ro: "La revedere / Pa", ru: "До свидания / Пока", cat: "💬 Фразы", emoji: "👋" },
    { ro: "Te pup", ru: "Целую", cat: "💬 Фразы", emoji: "💋" },
    { ro: "O zi bună", ru: "Хорошего дня", cat: "💬 Фразы", emoji: "✨" },
    { ro: "Ce faci?", ru: "Как дела? (Что делаешь?)", cat: "💬 Фразы", emoji: "💬" },
    { ro: "Bine", ru: "Хорошо", cat: "💬 Фразы", emoji: "👍" },
    { ro: "Așa și așa", ru: "Так себе", cat: "💬 Фразы", emoji: "🤷‍♀️" },
    { ro: "Am o întrebare", ru: "У меня вопрос", cat: "💬 Фразы", emoji: "❓" },
    { ro: "Cum te cheamă?", ru: "Как тебя зовут?", cat: "💬 Фразы", emoji: "🪪" },
    { ro: "Câți ani ai?", ru: "Сколько тебе лет?", cat: "💬 Фразы", emoji: "🎂" },
    { ro: "De unde ești?", ru: "Откуда ты?", cat: "💬 Фразы", emoji: "🌍" },
    { ro: "Îmi pare bine!", ru: "Мне приятно!", cat: "💬 Фразы", emoji: "🤝" },
    { ro: "Dar tu?", ru: "А ты?", cat: "💬 Фразы", emoji: "👉" },

    // 🛒 Супермаркет (Мясо, Молоко, Базовые продукты)
    { ro: "La cumpărături", ru: "За покупками", cat: "🛒 Супермаркет", emoji: "🛒" },
    { ro: "Lactate", ru: "Молочные продукты", cat: "🛒 Супермаркет", emoji: "🥛" },
    { ro: "Carne", ru: "Мясо", cat: "🛒 Супермаркет", emoji: "🥩" },
    { ro: "Lapte", ru: "Молоко", cat: "🛒 Супермаркет", emoji: "🥛" },
    { ro: "Lapte fără lactoză", ru: "Безлактозное молоко", cat: "🛒 Супермаркет", emoji: "🥛" },
    { ro: "Lapte condensat", ru: "Сгущенное молоко", cat: "🛒 Супермаркет", emoji: "🥫" },
    { ro: "Iaurt", ru: "Йогурт", cat: "🛒 Супермаркет", emoji: "🥣" },
    { ro: "Iaurt de băut", ru: "Питьевой йогурт", cat: "🛒 Супермаркет", emoji: "🥤" },
    { ro: "Brânză de vaci", ru: "Творог (коровий)", cat: "🛒 Супермаркет", emoji: "🧀" },
    { ro: "Cașcaval", ru: "Твердый сыр", cat: "🛒 Супермаркет", emoji: "🧀" },
    { ro: "Telemea", ru: "Брынза", cat: "🛒 Супермаркет", emoji: "🧀" },
    { ro: "Brânză de oi", ru: "Овечий сыр", cat: "🛒 Супермаркет", emoji: "🧀" },
    { ro: "Brânză de capră", ru: "Козий сыр", cat: "🛒 Супермаркет", emoji: "🧀" },
    { ro: "Brânză topită", ru: "Плавленый сыр", cat: "🛒 Супермаркет", emoji: "🧀" },
    { ro: "Urdă", ru: "Урда (мягкий сыр)", cat: "🛒 Супермаркет", emoji: "🧀" },
    { ro: "Smântână", ru: "Сметана", cat: "🛒 Супермаркет", emoji: "🥣" },
    { ro: "Unt", ru: "Сливочное масло", cat: "🛒 Супермаркет", emoji: "🧈" },
    { ro: "Carne de porc", ru: "Свинина", cat: "🛒 Супермаркет", emoji: "🥩" },
    { ro: "Carne de pui", ru: "Курятина", cat: "🛒 Супермаркет", emoji: "🍗" },
    { ro: "Carne de vită", ru: "Говядина", cat: "🛒 Супермаркет", emoji: "🥩" },
    { ro: "Carne de mânzat", ru: "Телятина", cat: "🛒 Супермаркет", emoji: "🥩" },
    { ro: "Carne tocată", ru: "Мясной фарш", cat: "🛒 Супермаркет", emoji: "🥩" },
    { ro: "Ceafă de porc", ru: "Свиная шея", cat: "🛒 Супермаркет", emoji: "🥩" },
    { ro: "Cotlet de porc", ru: "Свиная отбивная", cat: "🛒 Супермаркет", emoji: "🥩" },
    { ro: "Piept de pui", ru: "Куриная грудка", cat: "🛒 Супермаркет", emoji: "🍗" },
    { ro: "Pulpă", ru: "Окорочок / Мякоть", cat: "🛒 Супермаркет", emoji: "🍗" },
    { ro: "Gambe", ru: "Голени", cat: "🛒 Супермаркет", emoji: "🍗" },
    { ro: "Copănele", ru: "Куриные ножки", cat: "🛒 Супермаркет", emoji: "🍗" },
    { ro: "Aripioare de pui", ru: "Куриные крылышки", cat: "🛒 Супермаркет", emoji: "🍗" },
    { ro: "Fără os", ru: "Без кости", cat: "🛒 Супермаркет", emoji: "🦴" },
    { ro: "Feliat", ru: "Нарезанный", cat: "🛒 Супермаркет", emoji: "🔪" },
    { ro: "Mici (Mititei)", ru: "Мичи (колбаски для гриля)", cat: "🛒 Супермаркет", emoji: "🍢" },
    { ro: "Cârnați", ru: "Колбаски", cat: "🛒 Супермаркет", emoji: "🌭" },
    { ro: "Crenvurști", ru: "Сосиски", cat: "🛒 Супермаркет", emoji: "🌭" },
    { ro: "Chiftele", ru: "Тефтели", cat: "🛒 Супермаркет", emoji: "🧆" },
    { ro: "Pârjoale", ru: "Котлеты", cat: "🛒 Супермаркет", emoji: "🧆" },
    { ro: "Salam", ru: "Колбаса (салями)", cat: "🛒 Супермаркет", emoji: "🥓" },
    { ro: "Șuncă", ru: "Ветчина", cat: "🛒 Супермаркет", emoji: "🥓" },
    { ro: "Șnițel", ru: "Шницель", cat: "🛒 Супермаркет", emoji: "🍛" },
    { ro: "Pește", ru: "Рыба", cat: "🛒 Супермаркет", emoji: "🐟" },
    { ro: "Pește afumat", ru: "Копченая рыба", cat: "🛒 Супермаркет", emoji: "🐟" },
    { ro: "Fructe de mare", ru: "Морепродукты", cat: "🛒 Супермаркет", emoji: "🦐" },
    { ro: "Caracatiță", ru: "Осьминог", cat: "🛒 Супермаркет", emoji: "🐙" },
    { ro: "Calamar", ru: "Кальмар", cat: "🛒 Супермаркет", emoji: "🦑" },
    { ro: "Creveți", ru: "Креветки", cat: "🛒 Супермаркет", emoji: "🍤" },
    { ro: "Scoici", ru: "Мидии", cat: "🛒 Супермаркет", emoji: "🦪" },
    { ro: "Rac", ru: "Рак", cat: "🛒 Супермаркет", emoji: "🦞" },
    { ro: "Macrou", ru: "Скумбрия", cat: "🛒 Супермаркет", emoji: "🐟" },

    // 🍎 Фрукты и Овощи
    { ro: "Fructe", ru: "Фрукты", cat: "🍎 Фрукты и Овощи", emoji: "🍎" },
    { ro: "Legume", ru: "Овощи", cat: "🍎 Фрукты и Овощи", emoji: "🥕" },
    { ro: "Măr", ru: "Яблоко", cat: "🍎 Фрукты и Овощи", emoji: "🍎" },
    { ro: "Pară", ru: "Груша", cat: "🍎 Фрукты и Овощи", emoji: "🍐" },
    { ro: "Banană", ru: "Банан", cat: "🍎 Фрукты и Овощи", emoji: "🍌" },
    { ro: "Portocală", ru: "Апельсин", cat: "🍎 Фрукты и Овощи", emoji: "🍊" },
    { ro: "Mandarină", ru: "Мандарин", cat: "🍎 Фрукты и Овощи", emoji: "🍊" },
    { ro: "Lămâie", ru: "Лимон", cat: "🍎 Фрукты и Овощи", emoji: "🍋" },
    { ro: "Struguri", ru: "Виноград", cat: "🍎 Фрукты и Овощи", emoji: "🍇" },
    { ro: "Căpșună", ru: "Клубника", cat: "🍎 Фрукты и Овощи", emoji: "🍓" },
    { ro: "Cireașă", ru: "Черешня", cat: "🍎 Фрукты и Овощи", emoji: "🍒" },
    { ro: "Vișină", ru: "Вишня", cat: "🍎 Фрукты и Овощи", emoji: "🍒" },
    { ro: "Piersică", ru: "Персик", cat: "🍎 Фрукты и Овощи", emoji: "🍑" },
    { ro: "Caisă", ru: "Абрикос", cat: "🍎 Фрукты и Овощи", emoji: "🍑" },
    { ro: "Prună", ru: "Слива", cat: "🍎 Фрукты и Овощи", emoji: "🫐" },
    { ro: "Pepene roșu", ru: "Арбуз", cat: "🍎 Фрукты и Овощи", emoji: "🍉" },
    { ro: "Pepene galben", ru: "Дыня", cat: "🍎 Фрукты и Овощи", emoji: "🍈" },
    { ro: "Zmeură", ru: "Малина", cat: "🍎 Фрукты и Овощи", emoji: "🫐" },
    { ro: "Kiwi", ru: "Киви", cat: "🍎 Фрукты и Овощи", emoji: "🥝" },
    { ro: "Rodie", ru: "Гранат", cat: "🍎 Фрукты и Овощи", emoji: "🍎" },
    { ro: "Ananas", ru: "Ананас", cat: "🍎 Фрукты и Овощи", emoji: "🍍" },
    { ro: "Fructe de pădure", ru: "Лесные ягоды", cat: "🍎 Фрукты и Овощи", emoji: "🫐" },
    { ro: "Cătină", ru: "Облепиха", cat: "🍎 Фрукты и Овощи", emoji: "🌿" },
    { ro: "Smochine", ru: "Инжир", cat: "🍎 Фрукты и Овощи", emoji: "🫒" },
    { ro: "Mure", ru: "Ежевика", cat: "🍎 Фрукты и Овощи", emoji: "🫐" },
    { ro: "Agrișe", ru: "Крыжовник", cat: "🍎 Фрукты и Овощи", emoji: "🍈" },
    { ro: "Coacăză", ru: "Смородина", cat: "🍎 Фрукты и Овощи", emoji: "🫐" },
    { ro: "Roșie", ru: "Помидор", cat: "🍎 Фрукты и Овощи", emoji: "🍅" },
    { ro: "Castravete", ru: "Огурец", cat: "🍎 Фрукты и Овощи", emoji: "🥒" },
    { ro: "Cartof", ru: "Картофель", cat: "🍎 Фрукты и Овощи", emoji: "🥔" },
    { ro: "Ceapă", ru: "Лук", cat: "🍎 Фрукты и Овощи", emoji: "🧅" },
    { ro: "Usturoi", ru: "Чеснок", cat: "🍎 Фрукты и Овощи", emoji: "🧄" },
    { ro: "Morcov", ru: "Морковь", cat: "🍎 Фрукты и Овощи", emoji: "🥕" },
    { ro: "Ardei gras", ru: "Болгарский перец", cat: "🍎 Фрукты и Овощи", emoji: "🫑" },
    { ro: "Varză", ru: "Капуста", cat: "🍎 Фрукты и Овощи", emoji: "🥬" },
    { ro: "Dovlecel", ru: "Кабачок", cat: "🍎 Фрукты и Овощи", emoji: "🥒" },
    { ro: "Vânătă", ru: "Баклажан", cat: "🍎 Фрукты и Овощи", emoji: "🍆" },
    { ro: "Conopidă", ru: "Цветная капуста", cat: "🍎 Фрукты и Овощи", emoji: "🥦" },
    { ro: "Broccoli", ru: "Брокколи", cat: "🍎 Фрукты и Овощи", emoji: "🥦" },
    { ro: "Ridiche", ru: "Редис", cat: "🍎 Фрукты и Овощи", emoji: "🍅" },
    { ro: "Sfeclă roșie", ru: "Свекла", cat: "🍎 Фрукты и Овощи", emoji: "🍠" },
    { ro: "Dovleac", ru: "Тыква", cat: "🍎 Фрукты и Овощи", emoji: "🎃" },
    { ro: "Fasole", ru: "Фасоль", cat: "🍎 Фрукты и Овощи", emoji: "🫘" },
    { ro: "Mazăre", ru: "Горох", cat: "🍎 Фрукты и Овощи", emoji: "🫛" },
    { ro: "Ciupercă", ru: "Гриб", cat: "🍎 Фрукты и Овощи", emoji: "🍄" },
    { ro: "Pătrunjel", ru: "Петрушка", cat: "🍎 Фрукты и Овощи", emoji: "🌿" },
    { ro: "Mărar", ru: "Укроп", cat: "🍎 Фрукты и Овощи", emoji: "🌿" },
    { ro: "Macriș", ru: "Щавель", cat: "🍎 Фрукты и Овощи", emoji: "🥬" },
    { ro: "Sparanghel", ru: "Спаржа", cat: "🍎 Фрукты и Овощи", emoji: "🥬" },
    { ro: "Hrean", ru: "Хрен", cat: "🍎 Фрукты и Овощи", emoji: "🥔" },
    { ro: "Măsline", ru: "Оливки", cat: "🍎 Фрукты и Овощи", emoji: "🫒" },
    { ro: "Praz", ru: "Лук-порей", cat: "🍎 Фрукты и Овощи", emoji: "🧅" },

    // 🥐 Выпечка и Бакалея
    { ro: "Produse făinoase", ru: "Мучные изделия", cat: "🥐 Выпечка и Бакалея", emoji: "🥐" },
    { ro: "Pâine", ru: "Хлеб", cat: "🥐 Выпечка и Бакалея", emoji: "🍞" },
    { ro: "Gogoși", ru: "Пончики", cat: "🥐 Выпечка и Бакалея", emoji: "🍩" },
    { ro: "Covrigi", ru: "Крендели / бублики", cat: "🥐 Выпечка и Бакалея", emoji: "🥨" },
    { ro: "Chifle", ru: "Булочки", cat: "🥐 Выпечка и Бакалея", emoji: "🥖" },
    { ro: "Plăcintă", ru: "Пирог", cat: "🥐 Выпечка и Бакалея", emoji: "🥧" },
    { ro: "Corn", ru: "Рогалик (круассан)", cat: "🥐 Выпечка и Бакалея", emoji: "🥐" },
    { ro: "Clătită", ru: "Блинчик", cat: "🥐 Выпечка и Бакалея", emoji: "🥞" },
    { ro: "Prăjitură", ru: "Пирожное / Торт", cat: "🥐 Выпечка и Бакалея", emoji: "🍰" },
    { ro: "Chec", ru: "Кекс", cat: "🥐 Выпечка и Бакалея", emoji: "🥮" },
    { ro: "Brioșe", ru: "Маффины", cat: "🥐 Выпечка и Бакалея", emoji: "🧁" },
    { ro: "Cereale", ru: "Хлопья / злаки", cat: "🥐 Выпечка и Бакалея", emoji: "🥣" },
    { ro: "Aluat", ru: "Тесто", cat: "🥐 Выпечка и Бакалея", emoji: "🥟" },
    { ro: "Foietaj cu drojdie", ru: "Слоеное дрожжевое тесто", cat: "🥐 Выпечка и Бакалея", emoji: "🥐" },
    { ro: "Tăiței", ru: "Лапша", cat: "🥐 Выпечка и Бакалея", emoji: "🍜" },
    { ro: "Făină", ru: "Мука", cat: "🥐 Выпечка и Бакалея", emoji: "🌾" },
    { ro: "Hrișcă", ru: "Гречка", cat: "🥐 Выпечка и Бакалея", emoji: "🍲" },
    { ro: "Praf de copt", ru: "Разрыхлитель", cat: "🥐 Выпечка и Бакалея", emoji: "🧂" },
    { ro: "Pesmet", ru: "Панировочные сухари", cat: "🥐 Выпечка и Бакалея", emoji: "🍞" },
    { ro: "Griș", ru: "Манка", cat: "🥐 Выпечка и Бакалея", emoji: "🥣" },

    // 🍷 Напитки и Сладости
    { ro: "Înghețată", ru: "Мороженое", cat: "🍷 Напитки и Сладости", emoji: "🍨" },
    { ro: "Apă", ru: "Вода", cat: "🍷 Напитки и Сладости", emoji: "💧" },
    { ro: "Apă carbogazoasă", ru: "Газированная вода", cat: "🍷 Напитки и Сладости", emoji: "🫧" },
    { ro: "Apă plată", ru: "Вода без газа", cat: "🍷 Напитки и Сладости", emoji: "💧" },
    { ro: "Suc", ru: "Сок", cat: "🍷 Напитки и Сладости", emoji: "🧃" },
    { ro: "Suc de fructe", ru: "Фруктовый сок", cat: "🍷 Напитки и Сладости", emoji: "🧃" },
    { ro: "Vin", ru: "Вино", cat: "🍷 Напитки и Сладости", emoji: "🍷" },
    { ro: "Vin dulce", ru: "Сладкое вино", cat: "🍷 Напитки и Сладости", emoji: "🍷" },
    { ro: "Vin sec", ru: "Сухое вино", cat: "🍷 Напитки и Сладости", emoji: "🍷" },
    { ro: "Vin demi sec", ru: "Полусухое вино", cat: "🍷 Напитки и Сладости", emoji: "🍷" },
    { ro: "Vin spumant", ru: "Игристое вино", cat: "🍷 Напитки и Сладости", emoji: "🥂" },
    { ro: "Pălincă / Țuică", ru: "Палинка / Цуйка", cat: "🍷 Напитки и Сладости", emoji: "🥃" },
    { ro: "Vișinată", ru: "Вишневая наливка", cat: "🍷 Напитки и Сладости", emoji: "🍷" },
    { ro: "Căpșunată", ru: "Клубничная наливка", cat: "🍷 Напитки и Сладости", emoji: "🍷" },
    { ro: "Bere", ru: "Пиво", cat: "🍷 Напитки и Сладости", emoji: "🍺" },
    { ro: "Ceai", ru: "Чай", cat: "🍷 Напитки и Сладости", emoji: "🍵" },
    { ro: "Ceai negru / verde", ru: "Черный / зеленый чай", cat: "🍷 Напитки и Сладости", emoji: "🍵" },
    { ro: "Ceai din plante", ru: "Травяной чай", cat: "🍷 Напитки и Сладости", emoji: "🫖" },
    { ro: "Lapte cu cacao", ru: "Молоко с какао", cat: "🍷 Напитки и Сладости", emoji: "☕" },
    { ro: "Miere", ru: "Мед", cat: "🍷 Напитки и Сладости", emoji: "🍯" },
    { ro: "Frișcă", ru: "Взбитые сливки", cat: "🍷 Напитки и Сладости", emoji: "🍦" },
    { ro: "Cu gheață", ru: "Со льдом", cat: "🍷 Напитки и Сладости", emoji: "🧊" },

    // 🧽 Быт и Уборка
    { ro: "Șervețele umede", ru: "Влажные салфетки", cat: "🧽 Быт и Уборка", emoji: "🧻" },
    { ro: "Prosoape de hârtie", ru: "Бумажные полотенца", cat: "🧽 Быт и Уборка", emoji: "🧻" },
    { ro: "Burete", ru: "Губка", cat: "🧽 Быт и Уборка", emoji: "🧽" },
    { ro: "Saci de gunoi", ru: "Мусорные пакеты", cat: "🧽 Быт и Уборка", emoji: "🗑️" },
    { ro: "Folie alimentară", ru: "Пищевая пленка", cat: "🧽 Быт и Уборка", emoji: "🌯" },
    { ro: "Folie de aluminiu", ru: "Фольга", cat: "🧽 Быт и Уборка", emoji: "🌯" },
    { ro: "Hârtie de copt", ru: "Бумага для выпечки", cat: "🧽 Быт и Уборка", emoji: "📜" },
    { ro: "Mănuși de menaj", ru: "Хозяйственные перчатки", cat: "🧽 Быт и Уборка", emoji: "🧤" },
    { ro: "Mătură", ru: "Метла / веник", cat: "🧽 Быт и Уборка", emoji: "🧹" },
    { ro: "Mop", ru: "Швабра", cat: "🧽 Быт и Уборка", emoji: "🧹" },
    { ro: "Maşină de spălat rufe", ru: "Стиральная машина", cat: "🧽 Быт и Уборка", emoji: "🧺" },
    { ro: "Maşină de spălat vase", ru: "Посудомоечная машина", cat: "🧽 Быт и Уборка", emoji: "🍽️" },
    { ro: "Praf de spălat", ru: "Стиральный порошок", cat: "🧽 Быт и Уборка", emoji: "🫧" },
    { ro: "Capsule de spălat", ru: "Капсулы для стирки", cat: "🧽 Быт и Уборка", emoji: "🫧" },
    { ro: "Gel pentru vase", ru: "Гель для мытья посуды", cat: "🧽 Быт и Уборка", emoji: "🧼" },

    // 💊 Аптека
    { ro: "Pastile", ru: "Таблетки", cat: "💊 Аптека", emoji: "💊" },
    { ro: "Sirop de tuse", ru: "Сироп от кашля", cat: "💊 Аптека", emoji: "🥄" },
    { ro: "Spray pentru gât", ru: "Спрей для горла", cat: "💊 Аптека", emoji: "💨" },
    { ro: "Spray pentru nas", ru: "Спрей для носа", cat: "💊 Аптека", emoji: "👃" },
    { ro: "Picături pentru ochi", ru: "Капли для глаз", cat: "💊 Аптека", emoji: "👁️" },
    { ro: "Ovule", ru: "Свечи (медицинские)", cat: "💊 Аптека", emoji: "💊" },
    { ro: "Apă oxigenată", ru: "Перекись водорода", cat: "💊 Аптека", emoji: "🧴" },
    { ro: "Cremă", ru: "Крем", cat: "💊 Аптека", emoji: "🧴" },
    { ro: "Unguent", ru: "Мазь", cat: "💊 Аптека", emoji: "🧴" },
    { ro: "Gel", ru: "Гель", cat: "💊 Аптека", emoji: "🧴" },
    { ro: "Vată", ru: "Вата", cat: "💊 Аптека", emoji: "☁️" },
    { ro: "Plasture", ru: "Пластырь", cat: "💊 Аптека", emoji: "🩹" },

    // 🚗 Транспорт и дороги
    { ro: "Mașină", ru: "Машина / автомобиль", cat: "🚗 Транспорт", emoji: "🚗" },
    { ro: "Autoturism", ru: "Легковой автомобиль", cat: "🚗 Транспорт", emoji: "🚙" },
    { ro: "Mașină electrică", ru: "Электромобиль", cat: "🚗 Транспорт", emoji: "⚡" },
    { ro: "Autobuz", ru: "Автобус", cat: "🚗 Транспорт", emoji: "🚌" },
    { ro: "Microbuz", ru: "Маршрутка / микроавтобус", cat: "🚗 Транспорт", emoji: "🚐" },
    { ro: "Troleibuz", ru: "Троллейбус", cat: "🚗 Транспорт", emoji: "🚎" },
    { ro: "Tramvai", ru: "Трамвай", cat: "🚗 Транспорт", emoji: "🚊" },
    { ro: "Tren", ru: "Поезд", cat: "🚗 Транспорт", emoji: "🚆" },
    { ro: "Metrou", ru: "Метро", cat: "🚗 Транспорт", emoji: "🚇" },
    { ro: "Avion", ru: "Самолет", cat: "🚗 Транспорт", emoji: "✈️" },
    { ro: "Elicopter", ru: "Вертолет", cat: "🚗 Транспорт", emoji: "🚁" },
    { ro: "Bicicletă", ru: "Велосипед", cat: "🚗 Транспорт", emoji: "🚲" },
    { ro: "Trotinetă", ru: "Самокат", cat: "🚗 Транспорт", emoji: "🛴" },
    { ro: "Motocicletă", ru: "Мотоцикл", cat: "🚗 Транспорт", emoji: "🏍️" },
    { ro: "Moped", ru: "Мопед", cat: "🚗 Транспорт", emoji: "🛵" },
    { ro: "Taxi", ru: "Такси", cat: "🚗 Транспорт", emoji: "🚕" },
    { ro: "Ambulanță", ru: "Скорая помощь", cat: "🚗 Транспорт", emoji: "🚑" },
    { ro: "Mașină de poliție", ru: "Полицейская машина", cat: "🚗 Транспорт", emoji: "🚓" },
    { ro: "Mașină de pompieri", ru: "Пожарная машина", cat: "🚗 Транспорт", emoji: "🚒" },
    { ro: "Camion", ru: "Грузовик", cat: "🚗 Транспорт", emoji: "🚚" },
    { ro: "Tir", ru: "Фура / тягач", cat: "🚗 Транспорт", emoji: "🚛" },
    { ro: "Remorcă", ru: "Прицеп", cat: "🚗 Транспорт", emoji: "🚜" },
    { ro: "Tractor", ru: "Трактор", cat: "🚗 Транспорт", emoji: "🚜" },
    { ro: "Vapor", ru: "Пароход / корабль", cat: "🚗 Транспорт", emoji: "🚢" },
    { ro: "Barcă", ru: "Лодка", cat: "🚗 Транспорт", emoji: "🛶" },
    { ro: "Iaht", ru: "Яхта", cat: "🚗 Транспорт", emoji: "⛵" },
    { ro: "Șosea", ru: "Шоссе / дорога", cat: "🚗 Транспорт", emoji: "🛣️" },
    { ro: "Autostradă", ru: "Автомагистраль", cat: "🚗 Транспорт", emoji: "🛣️" },
    { ro: "Stradă", ru: "Улица", cat: "🚗 Транспорт", emoji: "🏙️" },
    { ro: "Pieton", ru: "Пешеход", cat: "🚗 Транспорт", emoji: "🚶" },
    { ro: "Trecere de pietoni", ru: "Пешеходный переход (зебра)", cat: "🚗 Транспорт", emoji: "🚸" },
    { ro: "Semafor", ru: "Светофор", cat: "🚗 Транспорт", emoji: "🚦" },
    { ro: "Parcare", ru: "Парковка", cat: "🚗 Транспорт", emoji: "🅿️" },
    { ro: "Stație", ru: "Остановка", cat: "🚗 Транспорт", emoji: "🚏" },
    { ro: "Aeroport", ru: "Аэропорт", cat: "🚗 Транспорт", emoji: "🛄" },
    { ro: "Gară", ru: "Вокзал", cat: "🚗 Транспорт", emoji: "🚉" },
    { ro: "Benzinărie", ru: "Заправка (АЗС)", cat: "🚗 Транспорт", emoji: "⛽" },
    { ro: "Șofer", ru: "Водитель", cat: "🚗 Транспорт", emoji: "👨‍✈️" },
    { ro: "Pasager", ru: "Пассажир", cat: "🚗 Транспорт", emoji: "🧍" },
    { ro: "Bilet", ru: "Билет", cat: "🚗 Транспорт", emoji: "🎫" },
    { ro: "Volan", ru: "Руль", cat: "🚗 Транспорт", emoji: "🔘" },
    { ro: "Roată", ru: "Колесо", cat: "🚗 Транспорт", emoji: "🛞" },
    { ro: "Frână", ru: "Тормоз", cat: "🚗 Транспорт", emoji: "🛑" },
    { ro: "Far", ru: "Фара", cat: "🚗 Транспорт", emoji: "💡" },
    { ro: "Motor", ru: "Двигатель / мотор", cat: "🚗 Транспорт", emoji: "⚙️" },
    { ro: "Ulei de motor", ru: "Моторное масло", cat: "🚗 Транспорт", emoji: "🛢️" },
    { ro: "Cisternă", ru: "Цистерна", cat: "🚗 Транспорт", emoji: "🚛" },
    { ro: "Buldozer", ru: "Бульдозер", cat: "🚗 Транспорт", emoji: "🚜" },
    { ro: "Macaraua", ru: "Кран (подъемный)", cat: "🚗 Транспорт", emoji: "🏗️" },
    { ro: "Trotuar", ru: "Тротуар", cat: "🚗 Транспорт", emoji: "🚶‍♂️" },

    // 💼 Жизнь и Профессии
    { ro: "Albastru", ru: "Синий", cat: "💼 Жизнь и Профессии", emoji: "🔵" },
    { ro: "Pălărie", ru: "Шляпа", cat: "💼 Жизнь и Профессии", emoji: "👒" },
    { ro: "Soare", ru: "Солнце", cat: "💼 Жизнь и Профессии", emoji: "☀️" },
    { ro: "Șaizeci și cinci", ru: "65", cat: "💼 Жизнь и Профессии", emoji: "65" },
    { ro: "Șaptezeci și cinci", ru: "75", cat: "💼 Жизнь и Профессии", emoji: "75" },
    { ro: "Liber", ru: "Свободен", cat: "💼 Жизнь и Профессии", emoji: "🟢" },
    { ro: "Ocupat", ru: "Занят", cat: "💼 Жизнь и Профессии", emoji: "🔴" },
    { ro: "Bărbat", ru: "Мужчина", cat: "💼 Жизнь и Профессии", emoji: "👨" },
    { ro: "Femeie", ru: "Женщина", cat: "💼 Жизнь и Профессии", emoji: "👩" },
    { ro: "Băiat", ru: "Мальчик", cat: "💼 Жизнь и Профессии", emoji: "👦" },
    { ro: "Fată", ru: "Девочка", cat: "💼 Жизнь и Профессии", emoji: "👧" },
    { ro: "Inginer", ru: "Инженер", cat: "💼 Жизнь и Профессии", emoji: "💻" },
    { ro: "Doctor", ru: "Врач / Медик", cat: "💼 Жизнь и Профессии", emoji: "🩺" },
    { ro: "Asistentă medicală", ru: "Медсестра", cat: "💼 Жизнь и Профессии", emoji: "👩‍⚕️" },
    { ro: "Polițist", ru: "Полицейский", cat: "💼 Жизнь и Профессии", emoji: "👮" },
    { ro: "Pompier", ru: "Пожарный", cat: "💼 Жизнь и Профессии", emoji: "👨‍🚒" },
    { ro: "Educatoare", ru: "Воспитательница", cat: "💼 Жизнь и Профессии", emoji: "🏫" },
    { ro: "Învățător", ru: "Учитель младших классов", cat: "💼 Жизнь и Профессии", emoji: "📚" },
    { ro: "Profesor", ru: "Преподаватель", cat: "💼 Жизнь и Профессии", emoji: "👨‍🏫" },
    { ro: "Bucătar", ru: "Повар", cat: "💼 Жизнь и Профессии", emoji: "👨‍🍳" },
    { ro: "Brutar", ru: "Пекарь", cat: "💼 Жизнь и Профессии", emoji: "🥖" },
    { ro: "Marinar", ru: "Моряк", cat: "💼 Жизнь и Профессии", emoji: "⚓" },
    { ro: "Chelner", ru: "Официант", cat: "💼 Жизнь и Профессии", emoji: "🍽️" },
    { ro: "Veterinar", ru: "Ветеринар", cat: "💼 Жизнь и Профессии", emoji: "🐾" },
    { ro: "Croitor", ru: "Портной", cat: "💼 Жизнь и Профессии", emoji: "🧵" },
    { ro: "Vânzător", ru: "Продавец", cat: "💼 Жизнь и Профессии", emoji: "🛍️" },
    { ro: "Zidar", ru: "Строитель", cat: "💼 Жизнь и Профессии", emoji: "🧱" },
    { ro: "Fermier", ru: "Фермер", cat: "💼 Жизнь и Профессии", emoji: "🚜" },
    { ro: "Instalator", ru: "Сантехник", cat: "💼 Жизнь и Профессии", emoji: "🔧" },
    { ro: "Contabil", ru: "Бухгалтер", cat: "💼 Жизнь и Профессии", emoji: "📊" },
    { ro: "Dentist", ru: "Стоматолог", cat: "💼 Жизнь и Профессии", emoji: "🦷" },
    { ro: "Programator", ru: "Программист", cat: "💼 Жизнь и Профессии", emoji: "💻" },
    { ro: "Manager", ru: "Менеджер", cat: "💼 Жизнь и Профессии", emoji: "📈" },
    { ro: "Poștaș", ru: "Почтальон", cat: "💼 Жизнь и Профессии", emoji: "✉️" },
    { ro: "Șofer", ru: "Водитель", cat: "💼 Жизнь и Профессии", emoji: "🚗" },
    { ro: "Măturător stradal", ru: "Дворник", cat: "💼 Жизнь и Профессии", emoji: "🧹" },
    { ro: "Cântăreț", ru: "Певец", cat: "💼 Жизнь и Профессии", emoji: "🎤" },
    { ro: "Actor", ru: "Актер", cat: "💼 Жизнь и Профессии", emoji: "🎭" },
    { ro: "Pictor", ru: "Художник", cat: "💼 Жизнь и Профессии", emoji: "🎨" },
    { ro: "Scriitor", ru: "Писатель", cat: "💼 Жизнь и Профессии", emoji: "✍️" },
    { ro: "Pescar", ru: "Рыбак", cat: "💼 Жизнь и Профессии", emoji: "🎣" },
    { ro: "Casnică", ru: "Домохозяйка", cat: "💼 Жизнь и Профессии", emoji: "🏠" },
    { ro: "Luni", ru: "Понедельник", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Marți", ru: "Вторник", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Miercuri", ru: "Среда", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Joi", ru: "Четверг", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Vineri", ru: "Пятница", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Sâmbătă", ru: "Суббота", cat: "💼 Жизнь и Профессии", emoji: "📅" },
    { ro: "Duminică", ru: "Воскресенье", cat: "💼 Жизнь и Профессии", emoji: "📅" },

    // 🧠 Тело и Здоровье
    { ro: "Cap", ru: "Голова", cat: "🧠 Тело и Здоровье", emoji: "🗣️" },
    { ro: "Păr", ru: "Волосы", cat: "🧠 Тело и Здоровье", emoji: "💇" },
    { ro: "Ureche", ru: "Ухо", cat: "🧠 Тело и Здоровье", emoji: "👂" },
    { ro: "Nas", ru: "Нос", cat: "🧠 Тело и Здоровье", emoji: "👃" },
    { ro: "Buză", ru: "Губа", cat: "🧠 Тело и Здоровье", emoji: "👄" },
    { ro: "Gură", ru: "Рот", cat: "🧠 Тело и Здоровье", emoji: "👄" },
    { ro: "Dinte", ru: "Зуб", cat: "🧠 Тело и Здоровье", emoji: "🦷" },
    { ro: "Limbă", ru: "Язык", cat: "🧠 Тело и Здоровье", emoji: "👅" },
    { ro: "Ochi", ru: "Глаз", cat: "🧠 Тело и Здоровье", emoji: "👁️" },
    { ro: "Gât", ru: "Шея / Горло", cat: "🧠 Тело и Здоровье", emoji: "🧣" },
    { ro: "Umăr", ru: "Плечо", cat: "🧠 Тело и Здоровье", emoji: "🤷" },
    { ro: "Cot", ru: "Локоть", cat: "🧠 Тело и Здоровье", emoji: "💪" },
    { ro: "Mână", ru: "Рука (кисть)", cat: "🧠 Тело и Здоровье", emoji: "✋" },
    { ro: "Braț", ru: "Рука (от плеча до кисти)", cat: "🧠 Тело и Здоровье", emoji: "💪" },
    { ro: "Deget", ru: "Палец", cat: "🧠 Тело и Здоровье", emoji: "☝️" },
    { ro: "Palmă", ru: "Ладонь", cat: "🧠 Тело и Здоровье", emoji: "🖐️" },
    { ro: "Burtă", ru: "Живот", cat: "🧠 Тело и Здоровье", emoji: "🤰" },
    { ro: "Stomac", ru: "Желудок", cat: "🧠 Тело и Здоровье", emoji: "🤢" },
    { ro: "Picior", ru: "Нога", cat: "🧠 Тело и Здоровье", emoji: "🦵" },
    { ro: "Genunchi", ru: "Колено", cat: "🧠 Тело и Здоровье", emoji: "🦵" },
    { ro: "Talpă", ru: "Ступня", cat: "🧠 Тело и Здоровье", emoji: "🦶" },
    { ro: "Sprânceană", ru: "Бровь", cat: "🧠 Тело и Здоровье", emoji: "🤨" },
    { ro: "Geană", ru: "Ресница", cat: "🧠 Тело и Здоровье", emoji: "👁️" },
    { ro: "Creier", ru: "Мозг", cat: "🧠 Тело и Здоровье", emoji: "🧠" },
    { ro: "Frunte", ru: "Лоб", cat: "🧠 Тело и Здоровье", emoji: "🤦" },
    { ro: "Ceafă", ru: "Затылок", cat: "🧠 Тело и Здоровье", emoji: "💆" },
    { ro: "Obraz", ru: "Щека", cat: "🧠 Тело и Здоровье", emoji: "😊" },
    { ro: "Barbă", ru: "Борода / Подбородок", cat: "🧠 Тело и Здоровье", emoji: "🧔" },
    { ro: "Mustață", ru: "Усы", cat: "🧠 Тело и Здоровье", emoji: "🧔" },
    { ro: "Piept", ru: "Грудь", cat: "🧠 Тело и Здоровье", emoji: "👕" },
    { ro: "Maxilar", ru: "Челюсть", cat: "🧠 Тело и Здоровье", emoji: "💀" },
    { ro: "Sân", ru: "Грудь (молочная железа)", cat: "🧠 Тело и Здоровье", emoji: "🤱" },
    { ro: "Inimă", ru: "Сердце", cat: "🧠 Тело и Здоровье", emoji: "❤️" },
    { ro: "Plămân", ru: "Легкое", cat: "🧠 Тело и Здоровье", emoji: "🫁" },
    { ro: "Ficat", ru: "Печень", cat: "🧠 Тело и Здоровье", emoji: "🥩" },
    { ro: "Rinichi", ru: "Почка", cat: "🧠 Тело и Здоровье", emoji: "🫘" },
    { ro: "Spate", ru: "Спина", cat: "🧠 Тело и Здоровье", emoji: "🔙" },
    { ro: "Ovar", ru: "Яичник", cat: "🧠 Тело и Здоровье", emoji: "♀️" },
    { ro: "Organe genitale", ru: "Половые органы", cat: "🧠 Тело и Здоровье", emoji: "🚻" },
    { ro: "Fund", ru: "Попа / дно", cat: "🧠 Тело и Здоровье", emoji: "🍑" },
    { ro: "Poponeață", ru: "Попка", cat: "🧠 Тело и Здоровье", emoji: "🍑" },
    { ro: "Subraț", ru: "Подмышка", cat: "🧠 Тело и Здоровье", emoji: "🙋" },
    { ro: "Buric", ru: "Пупок", cat: "🧠 Тело и Здоровье", emoji: "🕳️" },
    { ro: "Coloana vertebrală", ru: "Позвоночник", cat: "🧠 Тело и Здоровье", emoji: "🦴" },
    { ro: "Lombară", ru: "Поясница", cat: "🧠 Тело и Здоровье", emoji: "🧍" },
    { ro: "Călcâi", ru: "Пятка", cat: "🧠 Тело и Здоровье", emoji: "🦶" },
    { ro: "Mușchi", ru: "Мышца", cat: "🧠 Тело и Здоровье", emoji: "💪" },
    { ro: "Piele", ru: "Кожа", cat: "🧠 Тело и Здоровье", emoji: "🖐🏽" },
    { ro: "Venă", ru: "Вена", cat: "🧠 Тело и Здоровье", emoji: "🩸" },
    { ro: "Sânge", ru: "Кровь", cat: "🧠 Тело и Здоровье", emoji: "🩸" },
    { ro: "Muci", ru: "Сопли", cat: "🧠 Тело и Здоровье", emoji: "🤧" },
    { ro: "Febră", ru: "Жар / температура", cat: "🧠 Тело и Здоровье", emoji: "🤒" },
    { ro: "Temperatură", ru: "Температура", cat: "🧠 Тело и Здоровье", emoji: "🌡️" },
    { ro: "Tuse", ru: "Кашель", cat: "🧠 Тело и Здоровье", emoji: "🗣️" },
    { ro: "Uscat", ru: "Сухой", cat: "🧠 Тело и Здоровье", emoji: "🏜️" },
    { ro: "Umed", ru: "Влажный", cat: "🧠 Тело и Здоровье", emoji: "💦" },
    { ro: "Pleoapă", ru: "Веко", cat: "🧠 Тело и Здоровье", emoji: "👁️" },
    { ro: "Tendon", ru: "Сухожилие", cat: "🧠 Тело и Здоровье", emoji: "🦵" },

    // 🐾 Животный мир
    { ro: "Animale domestice", ru: "Домашние животные", cat: "🐾 Животный мир", emoji: "🏡" },
    { ro: "Animale sălbatice", ru: "Дикие животные", cat: "🐾 Животный мир", emoji: "🌲" },
    { ro: "Găină", ru: "Курица", cat: "🐾 Животный мир", emoji: "🐔" },
    { ro: "Pui", ru: "Цыпленок", cat: "🐾 Животный мир", emoji: "🐥" },
    { ro: "Cocoș", ru: "Петух", cat: "🐾 Животный мир", emoji: "🐓" },
    { ro: "Vacă", ru: "Корова", cat: "🐾 Животный мир", emoji: "🐄" },
    { ro: "Bou", ru: "Бык", cat: "🐾 Животный мир", emoji: "🐂" },
    { ro: "Vițel", ru: "Теленок", cat: "🐾 Животный мир", emoji: "🐮" },
    { ro: "Oaie", ru: "Овца", cat: "🐾 Животный мир", emoji: "🐑" },
    { ro: "Berbec", ru: "Баран", cat: "🐾 Животный мир", emoji: "🐏" },
    { ro: "Miel", ru: "Ягненок", cat: "🐾 Животный мир", emoji: "🐑" },
    { ro: "Capră", ru: "Коза", cat: "🐾 Животный мир", emoji: "🐐" },
    { ro: "Țap", ru: "Козел", cat: "🐾 Животный мир", emoji: "🐐" },
    { ro: "Ied", ru: "Козленок", cat: "🐾 Животный мир", emoji: "🐐" },
    { ro: "Cal", ru: "Лошадь", cat: "🐾 Животный мир", emoji: "🐎" },
    { ro: "Iapă", ru: "Кобыла", cat: "🐾 Животный мир", emoji: "🐎" },
    { ro: "Armăsar", ru: "Жеребец", cat: "🐾 Животный мир", emoji: "🐎" },
    { ro: "Mânz", ru: "Жеребенок", cat: "🐾 Животный мир", emoji: "🐴" },
    { ro: "Porc", ru: "Свинья", cat: "🐾 Животный мир", emoji: "🐖" },
    { ro: "Scroafă", ru: "Свиноматка", cat: "🐾 Животный мир", emoji: "🐖" },
    { ro: "Purcel", ru: "Поросенок", cat: "🐾 Животный мир", emoji: "🐷" },
    { ro: "Iepure", ru: "Заяц / Кролик", cat: "🐾 Животный мир", emoji: "🐇" },
    { ro: "Rață", ru: "Утка", cat: "🐾 Животный мир", emoji: "🦆" },
    { ro: "Rațoi", ru: "Селезень", cat: "🐾 Животный мир", emoji: "🦆" },
    { ro: "Boboc de rață", ru: "Утенок", cat: "🐾 Животный мир", emoji: "🐤" },
    { ro: "Gâscă", ru: "Гусь", cat: "🐾 Животный мир", emoji: "🪿" },
    { ro: "Gâscan", ru: "Гусак", cat: "🐾 Животный мир", emoji: "🪿" },
    { ro: "Boboc de gâscă", ru: "Гусенок", cat: "🐾 Животный мир", emoji: "🐤" },
    { ro: "Curcan", ru: "Индюк", cat: "🐾 Животный мир", emoji: "🦃" },
    { ro: "Curcă", ru: "Индюшка", cat: "🐾 Животный мир", emoji: "🦃" },
    { ro: "Măgar", ru: "Осел", cat: "🐾 Животный мир", emoji: "🫏" },
    { ro: "Câine", ru: "Собака", cat: "🐾 Животный мир", emoji: "🐕" },
    { ro: "Dulău", ru: "Пес", cat: "🐾 Животный мир", emoji: "🐕‍🦺" },
    { ro: "Cățea", ru: "Собака-девочка", cat: "🐾 Животный мир", emoji: "🐕" },
    { ro: "Cățel", ru: "Щенок", cat: "🐾 Животный мир", emoji: "🐶" },
    { ro: "Pisică", ru: "Кошка", cat: "🐾 Животный мир", emoji: "🐈" },
    { ro: "Motan", ru: "Кот", cat: "🐾 Животный мир", emoji: "🐈" },
    { ro: "Pisoi", ru: "Котенок", cat: "🐾 Животный мир", emoji: "🐱" },
    { ro: "Șoarece", ru: "Мышь", cat: "🐾 Животный мир", emoji: "🐁" },
    { ro: "Șobolan", ru: "Крыса", cat: "🐾 Животный мир", emoji: "🐀" },
    { ro: "Hamster", ru: "Хомяк", cat: "🐾 Животный мир", emoji: "🐹" },
    { ro: "Papagal", ru: "Попугай", cat: "🐾 Животный мир", emoji: "🦜" },
    { ro: "Porc de Guineea", ru: "Морская свинка", cat: "🐾 Животный мир", emoji: "🐹" },
    { ro: "Gândac", ru: "Жук", cat: "🐾 Животный мир", emoji: "🪲" },
    { ro: "Carcalac", ru: "Таракан", cat: "🐾 Животный мир", emoji: "🪳" },
    { ro: "Purice", ru: "Блоха", cat: "🐾 Животный мир", emoji: "🦟" },
    { ro: "Căpușă", ru: "Клещ", cat: "🐾 Животный мир", emoji: "🕷️" },
    { ro: "Păduche", ru: "Вошь", cat: "🐾 Животный мир", emoji: "🐛" },
    { ro: "Țânțar", ru: "Комар", cat: "🐾 Животный мир", emoji: "🦟" },
    { ro: "Muscă", ru: "Муха", cat: "🐾 Животный мир", emoji: "🪰" },
    { ro: "Păianjen", ru: "Паук", cat: "🐾 Животный мир", emoji: "🕷️" },
    { ro: "Porumbel", ru: "Голубь", cat: "🐾 Животный мир", emoji: "🕊️" },
    { ro: "Gărgăriță", ru: "Божья коровка", cat: "🐾 Животный мир", emoji: "🐞" },
    { ro: "Fluture", ru: "Бабочка", cat: "🐾 Животный мир", emoji: "🦋" },
    { ro: "Albină", ru: "Пчела", cat: "🐾 Животный мир", emoji: "🐝" },
    { ro: "Leu", ru: "Лев", cat: "🐾 Животный мир", emoji: "🦁" },
    { ro: "Raton", ru: "Енот", cat: "🐾 Животный мир", emoji: "🦝" },
    { ro: "Tigru", ru: "Тигр", cat: "🐾 Животный мир", emoji: "🐅" },
    { ro: "Girafă", ru: "Жираф", cat: "🐾 Животный мир", emoji: "🦒" },
    { ro: "Leoaică", ru: "Львица", cat: "🐾 Животный мир", emoji: "🦁" },
    { ro: "Șopârlă", ru: "Ящерица", cat: "🐾 Животный мир", emoji: "🦎" },
    { ro: "Șarpe", ru: "Змея", cat: "🐾 Животный мир", emoji: "🐍" },
    { ro: "Urs", ru: "Медведь", cat: "🐾 Животный мир", emoji: "🐻" },
    { ro: "Broască țestoasă", ru: "Черепаха", cat: "🐾 Животный мир", emoji: "🐢" },
    { ro: "Broască", ru: "Лягушка", cat: "🐾 Животный мир", emoji: "🐸" },
    { ro: "Lup", ru: "Волк", cat: "🐾 Животный мир", emoji: "🐺" },
    { ro: "Vulpe", ru: "Лиса", cat: "🐾 Животный мир", emoji: "🦊" },
    { ro: "Maimuță", ru: "Обезьяна", cat: "🐾 Животный мир", emoji: "🐵" },
    { ro: "Veveriță", ru: "Белка", cat: "🐾 Животный мир", emoji: "🐿️" },
    { ro: "Cerb", ru: "Олень", cat: "🐾 Животный мир", emoji: "🦌" },
    { ro: "Elan", ru: "Лось", cat: "🐾 Животный мир", emoji: "🫎" },
    { ro: "Ren", ru: "Северный олень", cat: "🐾 Животный мир", emoji: "🦌" },
    { ro: "Căprioară", ru: "Косуля", cat: "🐾 Животный мир", emoji: "🦌" },
    { ro: "Arici", ru: "Еж", cat: "🐾 Животный мир", emoji: "🦔" },
    { ro: "Cămilă", ru: "Верблюд", cat: "🐾 Животный мир", emoji: "🐪" },
    { ro: "Elefant", ru: "Слон", cat: "🐾 Животный мир", emoji: "🐘" },
    { ro: "Lebădă", ru: "Лебедь", cat: "🐾 Животный мир", emoji: "🦢" },
    { ro: "Crocodil", ru: "Крокодил", cat: "🐾 Животный мир", emoji: "🐊" },
    { ro: "Hipopotam", ru: "Бегемот", cat: "🐾 Животный мир", emoji: "🦛" },
    { ro: "Rinocer", ru: "Носорог", cat: "🐾 Животный мир", emoji: "🦏" },
    { ro: "Mistreț", ru: "Кабан", cat: "🐾 Животный мир", emoji: "🐗" },
    { ro: "Unicorn", ru: "Единорог", cat: "🐾 Животный мир", emoji: "🦄" },
    { ro: "Balenă", ru: "Кит", cat: "🐾 Животный мир", emoji: "🐋" },
    { ro: "Bovine", ru: "Крупный рогатый скот", cat: "🐾 Животный мир", emoji: "🐄" },
    { ro: "Zimbru", ru: "Зубр", cat: "🐾 Животный мир", emoji: "🐃" },
    { ro: "Zebră", ru: "Зебра", cat: "🐾 Животный мир", emoji: "🦓" },
    { ro: "Bivol", ru: "Буйвол", cat: "🐾 Животный мир", emoji: "🐃" },
    { ro: "Focă", ru: "Тюлень", cat: "🐾 Животный мир", emoji: "🦭" },
    { ro: "Morsă", ru: "Морж", cat: "🐾 Животный мир", emoji: "🦭" },
    { ro: "Rechin", ru: "Акула", cat: "🐾 Животный мир", emoji: "🦈" },
    { ro: "Delfin", ru: "Дельфин", cat: "🐾 Животный мир", emoji: "🐬" },
    { ro: "Sirenă", ru: "Русалка", cat: "🐾 Животный мир", emoji: "🧜‍♀️" },
    { ro: "Gorilă", ru: "Горилла", cat: "🐾 Животный мир", emoji: "🦍" },
    { ro: "Cimpanzeu", ru: "Шимпанзе", cat: "🐾 Животный мир", emoji: "🦧" },
    { ro: "Cangur", ru: "Кенгуру", cat: "🐾 Животный мир", emoji: "🦘" },
    { ro: "Cârtiță", ru: "Крот", cat: "🐾 Животный мир", emoji: "🦡" },
    { ro: "Greier", ru: "Сверчок", cat: "🐾 Животный мир", emoji: "🦗" },
    { ro: "Lăcustă", ru: "Саранча", cat: "🐾 Животный мир", emoji: "🦗" },
    { ro: "Licurici", ru: "Светлячок", cat: "🐾 Животный мир", emoji: "✨" },
    { ro: "Liliac", ru: "Летучая мышь", cat: "🐾 Животный мир", emoji: "🦇" },
    { ro: "Bufniță", ru: "Сова", cat: "🐾 Животный мир", emoji: "🦉" },
    { ro: "Vultur", ru: "Орел", cat: "🐾 Животный мир", emoji: "🦅" }
];

const userSentences = [
    { ro: "Eu sunt scriitor, dar el este marinar.", ru: "Я писатель, но он маринар." },
    { ro: "Tu ești doctor, dar ea este asistentă medicală.", ru: "Ты врач, но она медсестра." },
    { ro: "Soțul meu este inginer, dar eu sunt manager.", ru: "Мой муж инженер, но я менеджер." },
    { ro: "Ea este casnică, dar tu ești contabil.", ru: "Она домохозяйка, но ты бухгалтер." },
    { ro: "Noi suntem polițiști, dar ei nu sunt pompieri.", ru: "Мы полицейские, но они не пожарные." },
    { ro: "Voi sunteți actori, dar noi suntem pictori.", ru: "Вы актеры, но мы художники." },
    { ro: "Ei sunt băieți, dar Petro și Lukas nu sunt fete.", ru: "Они мальчики, но Петро и Лукас не девочки." },
    { ro: "Eu sunt femeie, dar el este bărbat.", ru: "Я женщина, но он мужчина." },
    { ro: "Eu sunt profesor, dar nu sunt inginer.", ru: "Я преподаватель, но не инженер." },
    { ro: "Tu ești doctor, dar nu ești veterinar.", ru: "Ты врач, но не ветеринар." },
    { ro: "El este programator, dar nu este manager.", ru: "Он программист, но не менеджер." },
    { ro: "Ea este asistentă medicală, dar nu este casnică.", ru: "Она медсестра, но не домохозяйка." },
    { ro: "Noi suntem polițiști, dar nu suntem pompieri.", ru: "Мы полицейские, но не пожарные." },
    { ro: "Dvs. sunteți instalator, dar nu sunteți șofer.", ru: "Вы (ув.) сантехник, но не водитель." },
    { ro: "Ei sunt băieți, dar nu sunt marinari.", ru: "Они мальчики, но не матросы." },
    { ro: "Ele sunt educatoare, dar nu sunt învățătoare.", ru: "Они (жен) воспитательницы, но не учительницы." },
    { ro: "El este zidar, dar nu este contabil.", ru: "Он строитель, но не бухгалтер." },
    { ro: "Eu sunt contabilă, dar nu lucrez.", ru: "Я бухгалтер (жен), но не работаю." },
    { ro: "Tu ești învățător, dar ea este croitor.", ru: "Ты учитель, но она портной." },
    { ro: "Voi cumpărați pâine.", ru: "Вы покупаете хлеб." },
    { ro: "Ei cumpără pesmeți.", ru: "Они покупают сухари." },
    { ro: "Noi cumpărăm praf de spălat.", ru: "Мы покупаем стиральный порошок." },
    { ro: "Tu nu cumperi flori.", ru: "Ты не покупаешь цветы." },
    { ro: "Tu cumperi brioșe și nu cumperi corn.", ru: "Ты покупаешь маффины и не покупаешь рогалик." },
    { ro: "Eu am lapte.", ru: "У меня есть молоко." },
    { ro: "Noi avem zahăr, dar noi nu avem sare.", ru: "У нас есть сахар, но у нас нет соли." },
    { ro: "El are mașină, dar el nu are bicicletă.", ru: "У него есть машина, но у него нет велосипеда." },
    { ro: "Ei au un câine, dar ei nu au o pisică.", ru: "У них есть собака, но у них нет кошки." }
];

const verbConjugations = [
    { verb: "a fi (быть)", pronoun: "Eu (Я)", form: "sunt", options: ["sunt", "ești", "este", "suntem"] },
    { verb: "a fi (быть)", pronoun: "Tu (Ты)", form: "ești", options: ["sunt", "ești", "sunteți", "este"] },
    { verb: "a fi (быть)", pronoun: "El / Ea (Он/Она)", form: "este", options: ["sunt", "este", "suntem", "ești"] },
    { verb: "a fi (быть)", pronoun: "Noi (Мы)", form: "suntem", options: ["suntem", "sunteți", "sunt", "este"] },
    { verb: "a fi (быть)", pronoun: "Voi / Dvs. (Вы)", form: "sunteți", options: ["sunteți", "suntem", "ești", "sunt"] },
    { verb: "a fi (быть)", pronoun: "Ei / Ele (Они)", form: "sunt", options: ["sunt", "este", "suntem", "sunteți"] },
    
    { verb: "a avea (иметь)", pronoun: "Eu (Я)", form: "am", options: ["am", "ai", "are", "avem"] },
    { verb: "a avea (иметь)", pronoun: "Tu (Ты)", form: "ai", options: ["am", "ai", "aveți", "au"] },
    { verb: "a avea (иметь)", pronoun: "El / Ea (Он/Она)", form: "are", options: ["avem", "are", "ai", "au"] },
    { verb: "a avea (иметь)", pronoun: "Noi (Мы)", form: "avem", options: ["aveți", "avem", "am", "are"] },
    { verb: "a avea (иметь)", pronoun: "Voi / Dvs. (Вы)", form: "aveți", options: ["avem", "aveți", "au", "ai"] },
    { verb: "a avea (иметь)", pronoun: "Ei / Ele (Они)", form: "au", options: ["are", "am", "au", "aveți"] },

    { verb: "a cumpăra (покупать)", pronoun: "Eu (Я)", form: "cumpăr", options: ["cumpăr", "cumperi", "cumpără", "cumpărăm"] },
    { verb: "a cumpăra (покупать)", pronoun: "Tu (Ты)", form: "cumperi", options: ["cumpăr", "cumperi", "cumpărați", "cumpără"] },
    { verb: "a cumpăra (покупать)", pronoun: "El / Ea (Он/Она)", form: "cumpără", options: ["cumperi", "cumpără", "cumpărăm", "cumpărați"] },
    { verb: "a cumpăra (покупать)", pronoun: "Noi (Мы)", form: "cumpărăm", options: ["cumpărați", "cumpărăm", "cumpăr", "cumpără"] },
    { verb: "a cumpăra (покупать)", pronoun: "Voi / Dvs. (Вы)", form: "cumpărați", options: ["cumperi", "cumpărați", "cumpărăm", "cumpăr"] },
    { verb: "a cumpăra (покупать)", pronoun: "Ei / Ele (Они)", form: "cumpără", options: ["cumpără", "cumpăr", "cumpărați", "cumperi"] }
];